[package]
name = "monolithica"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/neevek/monolithica"
description = "Some utilities"
keywords = ["utils", "utilities"]
categories = ["accessibility"]

[dependencies]
tracing = "0.1"
anyhow = "1.0"
mime_guess = "2.0"
